### ISSUE TITLE
Deployed app is not visible in the html5-apps-repo

### ISSUE THREAD

**Issue by archetypon** [ui5-community/generator-ui5-project#49]
## Easy-Ui5 version: 
3.4.0

## OS/version: 
Windows 10

## Browser/version (+device/version): 
Not relevant

## Steps to reproduce the problem:

1. Generate a new project (using platform _SAP HTML5 Application Repository service for SAP BTP_ )
2. run command _npm run deploy_

## What is the expected result?
The app should be visible in the BTP cockpit under HTML5 Applications

## What happens instead?
A configuration error is shown:
`- Destination [redacted] points to the html5-apps-repo instance [redacted], which does not contain any HTML5 applications.
It could be that the HTML5 applications for the html5-apps-repo instance [redacted] were not uploaded correctly.
You can try to redeploy the HTML5 applications.`

## Any other information? (attach screenshot if possible)
Please refer to [this](https://answers.sap.com/questions/13620104/destination-points-to-the-html5-apps-repo-instance.html) question, the last response resolve the issue.

**Comment by nicogeburek** [comment]
Hi @archetypon,

Good catch!

I believe we are actually missing two things:

1. The additional configuration in the `manifest.json`:
  ```json
  "sap.cloud": {
    "public": true,
    "service": "cloud.service"
  }
  ```
2. The configuration of the destination content as a new module in the `mta.yaml`:
  ```yaml
    - name: myUI5App_destination_content
      type: com.sap.application.content
      build-parameters:
        no-source: true
      requires:
        - name: myUI5App_uaa
          parameters:
            service-key:
              name: myUI5App_uaa_key
        - name: myUI5App_html5_repo_host
          parameters:
            service-key:
              name: myUI5App_html5_repo_host_key
        - name: myUI5App_destination
          parameters:
           content-target: true
      parameters:
        content:
          instance:
            existing_destinations_policy: update
            destinations:
              - Name: myUI5App_destination_html5
                ServiceInstanceName: myUI5App_html5_repo_host
                ServiceKeyName: myUI5App_html5_repo_host_key
                sap.cloud.service: cloud.service
              - Name: myUI5App_destination_uaa
                Authentication: OAuth2UserTokenExchange
                ServiceInstanceName: myUI5App_uaa
                ServiceKeyName: myUI5App_uaa_key
                sap.cloud.service: cloud.service
  ```

Adding both of those snippets fixes the issue and the application will be listed in the SAP BTP Cockpit under HTML5 Applications.

I will try to find out what options we have to build this into the generator. I will keep the issue open for reference.

Hope this helps.

BR, Nico
